Repository AdaSupport/ios-sdk, pull requests merged in 2022-06, with the labels that each got.

#52 chatx-1326: adding set device token
  EmbedFramework/AdaWebHost.swift
Labels: size/S

#55 Incrementing podspec
  AdaEmbedFramework.podspec
Labels: size/XS

#57 SUP-1101: Add header background for modal view
  AdaEmbedFramework.podspec
  EmbedFramework/AdaWebHost.swift
  ExampleApp/ViewController.swift
Labels: size/M, Impact - L2
